using System.Xml;
using Effortless.Cli.Project;
using Effortless.Cli.Text;

namespace Effortless.Cli.FileSets;

public static class ZfsLedger
{
    public static FileInfo GetZFSFI(
        EffortlessProject project,
        string transpilerKey,
        string cwd)
    {
        string relPath = GetCurrentRelativePath(
            project,
            transpilerKey,
            cwd);
        var ledgerDI = project.GetEffortlessDI();

        var zfsFileName = string.Format(
            "{0}/{1}/{2}.zfs",
            ledgerDI.FullName,
            relPath,
            transpilerKey);
        return new FileInfo(zfsFileName);
    }

    public static void SavePreviousFileSet(
        EffortlessProject project,
        string transpilerKey,
        string cwd,
        string fileSetXml,
        bool debug = false)
    {
        if (project is null)
        {
            return;
        }

        var zfsFI = GetZFSFI(project, transpilerKey, cwd);
        if (!zfsFI.Directory.Exists)
        {
            zfsFI.Directory.Create();
        }

        File.WriteAllBytes(zfsFI.FullName, fileSetXml.Zip());

        if (debug)
        {
            var debugXmlPath = Path.Combine(
                zfsFI.Directory.FullName,
                $"{transpilerKey}.xml");
            File.WriteAllText(debugXmlPath, fileSetXml);
            System.Console.WriteLine(
                $"DEBUG: Saved transpiler XML output to: {debugXmlPath}");
        }
    }

    public static string GetCurrentRelativePath(
        EffortlessProject project,
        string transpilerKey,
        string cwd)
    {
        string curDir = string.Empty;
        try
        {
            curDir = cwd ?? Environment.CurrentDirectory;
        }
        catch (Exception)
        {
            curDir = string.Empty;
        }

        string relPath;
        if (!string.IsNullOrEmpty(curDir) &&
            curDir.StartsWith(
                project.RootPath,
                StringComparison.OrdinalIgnoreCase))
        {
            relPath = curDir.Substring(project.RootPath.Length);
            relPath = relPath.Replace('\\', '/').TrimStart('/');
        }
        else
        {
            relPath = "";
        }

        return relPath;
    }

    /// <summary>
    /// Detects the "in-place upsert" shape and downgrades it to OverwriteMode=Never
    /// <em>inside the FileSet XML itself</em>, returning the rewritten XML.
    /// </summary>
    /// <remarks>
    /// The shape, and the entire detection condition, is:
    ///
    ///   1) an input file was sent to the transpiler at some relative path, and
    ///   2) the result contains an output file at that <em>same</em> resolved path,
    ///      declared OverwriteMode=Always (or AlwaysOverwrite=true).
    ///
    /// That is a tool rewriting its own input in place (compile-rulebook is the first,
    /// but the rule keys on the shape, never on a tool, a file name, or a path). Such a
    /// file is authored by the user, not generated by us: it must never be entered in
    /// the .zfs ledger as a file we own, or the content-match clean pass will delete it
    /// the moment the user hand-edits it — which is exactly the documented, intentional
    /// behavior for a genuinely generated Always file, and exactly wrong for this one.
    ///
    /// The downgrade is applied to the FileSet XML before anything else consumes it, so
    /// every downstream stage — the clean pass, FileSetWriter, and the ledger that is
    /// persisted for future cleans — sees a plain OverwriteMode=Never file and leaves
    /// the user's file alone. Writing still happens: <see cref="SaveFileSet"/> splits the
    /// downgraded FileSet with overwriteAll enabled for exactly these paths, so the
    /// upsert lands, but nothing downstream believes we own the file.
    ///
    /// The transpiler needs to know none of this. It keeps declaring Always, which is
    /// the honest declaration of intent ("I am rewriting this file"); the CLI is the only
    /// layer that can see both sides of the exchange, so the rule lives here.
    /// </remarks>
    public static string DowngradeInPlaceUpserts(
        EffortlessProject project,
        string inputFileSetXml,
        string fileSetXml,
        string extractToDir,
        out HashSet<string> downgradedFullPaths,
        bool debug = false)
    {
        downgradedFullPaths = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        if (project is null || string.IsNullOrEmpty(inputFileSetXml))
        {
            return fileSetXml;
        }

        if (string.IsNullOrEmpty(fileSetXml) || !fileSetXml.Contains("<"))
        {
            return fileSetXml;
        }

        var inputFullPaths = GetInputFullPaths(project, inputFileSetXml);
        if (!inputFullPaths.Any())
        {
            return fileSetXml;
        }

        XmlDocument doc;
        try
        {
            doc = new XmlDocument();
            doc.LoadXml(fileSetXml.Substring(fileSetXml.IndexOf("<")));
        }
        catch (Exception)
        {
            return fileSetXml;
        }

        if (doc.DocumentElement is null ||
            doc.DocumentElement.Name != "FileSet")
        {
            return fileSetXml;
        }

        var changed = false;
        foreach (XmlElement fsfElem in
                 doc.DocumentElement.SelectNodes("//FileSetFile"))
        {
            if (!IsAlwaysOverwriteElement(fsfElem))
            {
                continue;
            }

            var matchedHere = false;
            foreach (XmlElement relPathElem in
                     fsfElem.SelectNodes("RelativePath"))
            {
                var outputFullPath = ResolveFullPath(
                    extractToDir,
                    relPathElem.InnerText);
                if (outputFullPath is null ||
                    !inputFullPaths.Contains(outputFullPath))
                {
                    continue;
                }

                matchedHere = true;
                downgradedFullPaths.Add(outputFullPath);

                if (debug)
                {
                    System.Console.WriteLine(
                        $"DEBUG: In-place upsert detected for {outputFullPath}; downgrading OverwriteMode Always -> Never so it is never ledgered as generated.");
                }
            }

            if (matchedHere)
            {
                SetOverwriteModeNever(fsfElem);
                changed = true;
            }
        }

        if (!changed)
        {
            return fileSetXml;
        }

        return doc.OuterXml;
    }

    private static HashSet<string> GetInputFullPaths(
        EffortlessProject project,
        string inputFileSetXml)
    {
        var inputFullPaths = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        try
        {
            foreach (var fsf in inputFileSetXml.ToFileSet().FileSetFiles)
            {
                if (string.IsNullOrEmpty(fsf.OriginalRelativePath))
                {
                    continue;
                }

                var fullPath = ResolveFullPath(
                    project.RootPath,
                    fsf.OriginalRelativePath);
                if (fullPath is not null)
                {
                    inputFullPaths.Add(fullPath);
                }
            }
        }
        catch (Exception)
        {
            return new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        }

        return inputFullPaths;
    }

    /// <summary>
    /// Resolves a FileSet relative path against a base directory into a single canonical
    /// full path. Separators are normalized so a tool that emits "/" and an input loader
    /// that recorded "\" (or vice versa) still compare equal, and the FileInfo pass
    /// collapses any "." / ".." segments so "-i effortless-rulebook.json" written from a
    /// step whose RelativePath is "/effortless-rulebook" resolves to the same string as
    /// the input file it was read from. Comparison is ordinal-ignore-case, matching the
    /// case-insensitive file systems on macOS and Windows.
    /// </summary>
    private static string ResolveFullPath(string baseDir, string relativePath)
    {
        var trimmed = relativePath.SafeToString()
            .Replace('\\', '/')
            .Trim("\r\n\t /".ToCharArray());
        if (string.IsNullOrEmpty(trimmed) || string.IsNullOrEmpty(baseDir))
        {
            return null;
        }

        try
        {
            return new FileInfo(Path.Combine(baseDir, trimmed)).FullName;
        }
        catch (Exception)
        {
            return null;
        }
    }

    private static void SetOverwriteModeNever(XmlElement fsfElem)
    {
        var aoNode = fsfElem.SelectSingleNode("AlwaysOverwrite");
        if (!ReferenceEquals(aoNode, null))
        {
            aoNode.InnerText = "false";
        }

        var omNode = fsfElem.SelectSingleNode("OverwriteMode");
        if (ReferenceEquals(omNode, null))
        {
            omNode = fsfElem.OwnerDocument.CreateElement("OverwriteMode");
            fsfElem.AppendChild(omNode);
        }

        omNode.InnerText = "Never";
    }

    /// <summary>
    /// Removes any ledger entry for a path that is now recognized as an in-place upsert.
    /// A project built before this rule existed has the user's own file recorded in its
    /// .zfs as a generated Always file; leaving that entry in place would let the very
    /// next clean delete the file, so the poisoned entry is pruned and such projects
    /// self-heal on their next build.
    /// </summary>
    public static string PruneLedgerEntries(
        string previousFileSetXml,
        HashSet<string> fullPathsToPrune,
        string extractToDir)
    {
        if (string.IsNullOrEmpty(previousFileSetXml) ||
            !previousFileSetXml.Contains("<") ||
            fullPathsToPrune is null ||
            !fullPathsToPrune.Any())
        {
            return previousFileSetXml;
        }

        XmlDocument doc;
        try
        {
            doc = new XmlDocument();
            doc.LoadXml(previousFileSetXml.Substring(previousFileSetXml.IndexOf("<")));
        }
        catch (Exception)
        {
            return previousFileSetXml;
        }

        if (doc.DocumentElement is null ||
            doc.DocumentElement.Name != "FileSet")
        {
            return previousFileSetXml;
        }

        var changed = false;
        foreach (XmlElement fsfElem in
                 doc.DocumentElement.SelectNodes("//FileSetFile").Cast<XmlElement>().ToList())
        {
            var matches = fsfElem.SelectNodes("RelativePath")
                .Cast<XmlElement>()
                .Select(rp => ResolveFullPath(extractToDir, rp.InnerText))
                .Any(fp => fp is not null && fullPathsToPrune.Contains(fp));
            if (matches)
            {
                fsfElem.ParentNode.RemoveChild(fsfElem);
                changed = true;
            }
        }

        return changed ? doc.OuterXml : previousFileSetXml;
    }

    /// <summary>
    /// Guards against a TOCTOU race: if a file was read as tool input and the tool's
    /// response wants to overwrite that same path with OverwriteMode=Always, the file
    /// must still match what was originally read, or the on-disk edit that happened
    /// while the tool was running would be silently clobbered.
    /// </summary>
    public static void ValidateSelfSourceOverwrites(
        EffortlessProject project,
        string inputFileSetXml,
        string fileSetXml,
        string extractToDir)
    {
        if (project is null || string.IsNullOrEmpty(inputFileSetXml))
        {
            return;
        }

        if (string.IsNullOrEmpty(fileSetXml) || !fileSetXml.Contains("<"))
        {
            return;
        }

        Dictionary<string, FileSetFile> inputByFullPath;
        try
        {
            inputByFullPath = inputFileSetXml
                .ToFileSet()
                .FileSetFiles
                .Where(fsf => !string.IsNullOrEmpty(fsf.OriginalRelativePath))
                .GroupBy(
                    fsf => new FileInfo(
                            Path.Combine(
                                project.RootPath,
                                fsf.OriginalRelativePath.Trim("\\/".ToCharArray())))
                        .FullName,
                    StringComparer.OrdinalIgnoreCase)
                .ToDictionary(g => g.Key, g => g.First(), StringComparer.OrdinalIgnoreCase);
        }
        catch (Exception)
        {
            return;
        }

        if (!inputByFullPath.Any())
        {
            return;
        }

        var doc = new XmlDocument();
        var trimmedXml = fileSetXml.Substring(fileSetXml.IndexOf("<"));
        doc.LoadXml(trimmedXml);
        if (doc.DocumentElement is null ||
            doc.DocumentElement.Name != "FileSet")
        {
            return;
        }

        foreach (XmlElement fsfElem in
                 doc.DocumentElement.SelectNodes("//FileSetFile"))
        {
            if (!IsAlwaysOverwriteElement(fsfElem))
            {
                continue;
            }

            foreach (XmlElement relPathElem in
                     fsfElem.SelectNodes("RelativePath"))
            {
                var outputFullPath = new FileInfo(
                        Path.Combine(
                            extractToDir,
                            relPathElem.InnerText.SafeToString()
                                .Trim("\\/".ToCharArray())))
                    .FullName;

                if (inputByFullPath.TryGetValue(outputFullPath, out var inputFsf))
                {
                    EnsureUnchangedSinceRead(inputFsf, outputFullPath);
                }
            }
        }
    }

    private static bool IsAlwaysOverwriteElement(XmlElement elem)
    {
        bool alwaysOverwrite = false;

        XmlNode aoNode = elem.SelectSingleNode("AlwaysOverwrite");
        if (!ReferenceEquals(aoNode, null) && aoNode.InnerText == "true")
        {
            alwaysOverwrite = true;
        }

        XmlNode omNode = elem.SelectSingleNode("OverwriteMode");
        if (!ReferenceEquals(omNode, null))
        {
            if (string.Equals(omNode.InnerText, "Always", StringComparison.OrdinalIgnoreCase))
            {
                alwaysOverwrite = true;
            }
            else if (string.Equals(omNode.InnerText, "Never", StringComparison.OrdinalIgnoreCase))
            {
                alwaysOverwrite = false;
            }
        }

        return alwaysOverwrite;
    }

    private static void EnsureUnchangedSinceRead(FileSetFile inputFsf, string fullPath)
    {
        if (!ReferenceEquals(inputFsf.ZippedBinaryFileContents, null))
        {
            var originalBytes = inputFsf.GetFileSetFileBinaryContents();
            var currentBytes = File.Exists(fullPath) ? File.ReadAllBytes(fullPath) : null;
            if (currentBytes is null || !originalBytes.SequenceEqual(currentBytes))
            {
                throw new Exception(
                    $"Refusing to overwrite '{fullPath}': it was read as tool input and changed on disk while the tool was running.");
            }

            return;
        }

        var originalText = inputFsf.GetFileSetFileContents();
        var currentText = File.Exists(fullPath) ? File.ReadAllText(fullPath) : null;
        if (currentText is null || currentText != originalText)
        {
            throw new Exception(
                $"Refusing to overwrite '{fullPath}': it was read as tool input and changed on disk while the tool was running.");
        }
    }

    public static int SaveFileSet(
        EffortlessProject project,
        string transpilerKey,
        string cwd,
        byte[] zippedOutputFileSet,
        string inputFileSetXml,
        bool skipClean,
        bool debug = false)
    {
        var fileSetXml = zippedOutputFileSet.UnzipToString();
        string workingDir = project.GetEffortlessDI().ToString();

        string extractToDir = project?.RootPath ?? workingDir;
        if (project != null)
        {
            var relPath = GetCurrentRelativePath(
                project,
                transpilerKey,
                cwd);
            if (!string.IsNullOrEmpty(relPath))
            {
                extractToDir = Path.Combine(project.RootPath, relPath);
            }
        }

        // An in-place upsert (input path == output path, declared Always) is the user's
        // own file, not a generated one. Detect it and downgrade it to Never in the
        // FileSet itself BEFORE anything else looks at the FileSet: the clean pass below,
        // the writer, and the ledger persisted at the end must all see Never so that no
        // future build treats the user's source of truth as ours to delete.
        fileSetXml = DowngradeInPlaceUpserts(
            project,
            inputFileSetXml,
            fileSetXml,
            extractToDir,
            out var inPlaceUpsertPaths,
            debug);

        // A project built before this rule existed already has the user's file recorded
        // in its .zfs as a generated Always file. Prune those entries before the clean
        // pass runs, so a previously poisoned project self-heals instead of losing the
        // file one last time on this build.
        if (inPlaceUpsertPaths.Any())
        {
            PrunePoisonedLedger(
                project,
                transpilerKey,
                cwd,
                inPlaceUpsertPaths,
                extractToDir,
                debug);
        }

        if (!skipClean)
        {
            CleanFileSet(
                project,
                transpilerKey,
                cwd,
                debug,
                deleteEmptyDirs: false);
        }

        ValidateSelfSourceOverwrites(project, inputFileSetXml, fileSetXml, extractToDir);

        var tempFI = new FileInfo(
            Path.Combine(
                workingDir,
                string.Format("tempFileSet_{0}.xml", Guid.NewGuid())));
        File.WriteAllText(tempFI.FullName, fileSetXml);

        // The downgraded entries now say Never, which would make the writer skip an
        // existing file. The upsert must still land, so those specific paths are written
        // unconditionally here. This is the one place that needs the set: everything
        // persisted or cleaned later sees only the Never declaration.
        tempFI.FullName.SplitFileSetFile(extractToDir, inPlaceUpsertPaths);
        tempFI.Delete();

        SavePreviousFileSet(
            project,
            transpilerKey,
            cwd,
            fileSetXml,
            debug);

        return 0;
    }

    /// <summary>
    /// Rewrites the on-disk .zfs for this transpiler with any entries for the given
    /// in-place-upsert paths removed, so a ledger poisoned by a build that predates this
    /// rule can no longer drive a delete of the user's own file.
    /// </summary>
    private static void PrunePoisonedLedger(
        EffortlessProject project,
        string transpilerKey,
        string cwd,
        HashSet<string> fullPathsToPrune,
        string extractToDir,
        bool debug)
    {
        var zfsFI = GetZFSFI(project, transpilerKey, cwd);
        if (!zfsFI.Exists)
        {
            return;
        }

        try
        {
            var previousXml = File.ReadAllBytes(zfsFI.FullName).UnzipToString();
            var prunedXml = PruneLedgerEntries(
                previousXml,
                fullPathsToPrune,
                extractToDir);
            if (!ReferenceEquals(prunedXml, previousXml) && prunedXml != previousXml)
            {
                File.WriteAllBytes(zfsFI.FullName, prunedXml.Zip());
                if (debug)
                {
                    System.Console.WriteLine(
                        $"DEBUG: Pruned stale in-place-upsert entries from {zfsFI.FullName}.");
                }
            }
        }
        catch (Exception ex)
        {
            if (debug)
            {
                System.Console.WriteLine(
                    $"DEBUG: Could not prune ledger {zfsFI.FullName}: {ex.Message}");
            }
        }
    }

    public static void CleanFileSet(
        EffortlessProject project,
        string transpilerKey,
        string cwd,
        bool debug = false,
        bool deleteEmptyDirs = true)
    {
        if (project is null)
        {
            return;
        }

        FileInfo zfsFI = GetZFSFI(project, transpilerKey, cwd);
        if (zfsFI.Exists)
        {
            var previousFileSet = File.ReadAllBytes(zfsFI.FullName);
            previousFileSet.CleanZippedFileSet(
                debug,
                deleteEmptyDirs);
        }
    }
}
